### ISSUE TITLE
This seems to be coming to node natively soon

### ISSUE THREAD

**Issue by morganney** [nktnet1/import-sync#113]
https://nodejs.org/api/modules.html#loading-ecmascript-modules-using-require

**Comment by nktnet1** [comment]
Yep - good news. Thanks for sharing @morganney!

import-sync will likely still be around to support older versions of Node, but this is a nice addition to NodeJS.

**Comment by morganney** [comment]
I don’t suppose you found a way to import a module using top level await? There doesn’t seem to be a way as the two module systems are fundamentally incompatible in this way. Sync vs Async.

**Comment by nktnet1** [comment]
I haven't looked too deeply - asynchronous imports are outside the scope of import-sync :).
The primary goal of this library was to synchronously import ESM to CJS (or vice versa) in NodeJS.

**Comment by morganney** [comment]
On that note I'll close this issue out, as it was mostly informative. Interesting project though 👍

**Comment by nktnet1** [comment]
Regarding asynchronous imports and top-level await - in case you're still interested, I suggest looking into Jiti:

- https://github.com/unjs/jiti

Example conversion here:

- https://github.com/nktnet-bug-report/import-sync-test/pull/1
