### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'startsWith')

### ISSUE THREAD

**Issue by chadxz** [nktnet1/import-sync#137]
Getting this error trying to use this library in [my toy project](https://github.com/chadxz/tally/blob/main/packages/typedconfig/src/load.ts#L101):

```
TypeError: Cannot read properties of undefined (reading 'startsWith')
    at getCallerDirname (/Users/chad/src/tally/node_modules/.pnpm/import-sync@2.2.2/node_modules/import-sync/dist/cjs/files.js:27:50)
    at Module.importSync (/Users/chad/src/tally/node_modules/.pnpm/import-sync@2.2.2/node_modules/import-sync/dist/cjs/import.js:41:108)
    at loadConfigFromFile (/Users/chad/src/tally/packages/typedconfig/src/load.ts:66:41)
    at loadAllConfigFiles (/Users/chad/src/tally/packages/typedconfig/src/load.ts:19:8)
    at Module.loadConfig (/Users/chad/src/tally/packages/typedconfig/src/load.ts:12:16)
    at eval (/Users/chad/src/tally/apps/web/app/config.ts:12:43)
    at async instantiateModule (file:///Users/chad/src/tally/node_modules/.pnpm/vite@5.4.7_@types+node@22.5.5/node_modules/vite/dist/node/chunks/dep-DG6Lorbi.js:52914:5)
```

Under debug, it looks like `stack[1].getFileName();` is returning `undefined` but `stack[1].getEvalOrigin()` returns `/Users/chad/src/tally/packages/typedconfig/src/load.ts` (this is probably what we want here?)

I don't know why getFileName() is returning undefined. I'm using remix so maybe it has something to do with it being bundled?

**Comment by nktnet1** [comment]
Hi @chadxz,

Which package are you trying to import specifically?
Or is it any package in general under your current environment/setup?

As an aside, I would also suggest looking into
- https://nodejs.org/api/modules.html#loading-ecmascript-modules-using-require
if you are on the latest node version.

**Comment by chadxz** [comment]
I'm trying to import a file in my project, i.e. https://github.com/chadxz/tally/blob/add805d165f26a1a2932587ee31cd869b75b9241/packages/typedconfig/src/load.ts#L41 would import https://github.com/chadxz/tally/blob/main/apps/web/config/default.ts

I can try using the built in support again. I'm using remix for the first time so there's a bunch of moving parts there I'm unfamiliar with. I think I will have to pass the experimental flag in a NODE_OPTIONS env var to `remix-serve` and `vite`. 

Anyway, I understand this package will soon be unneeded so it's unlikely to get changes. I'll see what I can do. Thx

**Comment by nktnet1** [comment]
Something you could try is removing the extension from the path and see if it would be picked up, e.g.

```ts
function loadConfigFromFile(path: string): NestedConfig {
  try {
    return importSync(path.replace(/\.[^/.]+$/, ""));
  } catch (e) {
    return {};
  }
}
```

**Comment by nktnet1** [comment]
Is it possible to use a serialised format like `JSON` for the config?

Then you can do `[fs.readFileSync](https://nodejs.org/api/fs.html#fsreadfilesyncpath-options)` to load the config, for example, and use something like [zod](https://zod.dev) for validation/parsing.

**Comment by chadxz** [comment]
Was trying to give develop-time syntax highlighting and code completion for the config, so JSON wouldn't work unless I generated some sort of JSON Schema from the Zod definition. I don't think I want that sort of build step in the mix.

**Comment by nktnet1** [comment]
In case you're still interested in solving this issue - I suggest looking into a library called Jiti:

- https://github.com/unjs/jiti

Example conversion here:

- https://github.com/nktnet-bug-report/import-sync-test/pull/1
