### ISSUE TITLE
Can't import some modules

### ISSUE THREAD

**Issue by pimterry** [nktnet1/import-sync#37]
One example: [node-datachannel](https://github.com/murat-dogan/node-datachannel/).

Create a new folder, and run:

```javascript
$ npm install import-sync node-datachannel
$ node
> importSync = require('import-sync')
> importSync('node-datachannel')
Uncaught Error: 
        Failed to import from:
            node-datachannel.
        Options:
            {}
        Require error message:
            /tmp/tmp.cGqoObetIA/node_modules/import-sync/dist/cjs/import.js:1
Error: Cannot find module 'node-datachannel'
Require stack:
- /tmp/tmp.cGqoObetIA/node_modules/import-sync/dist/cjs/import.js
- /tmp/tmp.cGqoObetIA/node_modules/import-sync/dist/cjs/index.js
- <repl>
    at esmImport (/tmp/tmp.cGqoObetIA/node_modules/import-sync/dist/cjs/import.js:47:16)
    at importSync (/tmp/tmp.cGqoObetIA/node_modules/import-sync/dist/cjs/import.js:72:28)
    at REPL4:1
    at Script.runInThisContext (node:vm:122:12)
    at REPLServer.defaultEval (node:repl:594:29)
    
    at esmImport (/tmp/tmp.cGqoObetIA/node_modules/import-sync/dist/cjs/import.js:50:15)
    at importSync (/tmp/tmp.cGqoObetIA/node_modules/import-sync/dist/cjs/import.js:72:28)

> await import('node-datachannel')
[Module: null prototype] {
  Audio: [Function: Audio],
  DataChannel: [Function: DataChannel],
  ... // I.e. it imports with ESM just fine
}
```

Happens with Node 20.8.0 and 21.4.0 (latest). Any idea what's going on here? Node-fetch does indeed import as expected, but this module isn't even found for some reason.

**Comment by nktnet1** [comment]
Hi @pimterry,

I briefly looked into [node-datachannel](https://github.com/murat-dogan/node-datachannel/) and there are two issues that I can see.

## Missing Main Field
node-datachannel missing a "main" field in its package.json
- https://github.com/murat-dogan/node-datachannel/blob/82db7e6643a977b97b5f3d551397e9ef50b3fa9a/package.json

This can be fixed by adding

```json
"main": "./lib/index.js",
```
at the top level.

## Redefining Require
The variable "require" is being redefined in lib/index.js at lines 3-5:
- https://github.com/murat-dogan/node-datachannel/blob/82db7e6643a977b97b5f3d551397e9ef50b3fa9a/lib/index.js#L3-L5

While this is fine in ESM, if you are trying to import this module into your CJS project, then you will get the `SyntaxError`:
> Identifier 'require' has already been declared

This can be fixed by simply calling the variable something else, e.g. in node-datachannel's lib/index.js, lines 3-5:
```js
```

**Comment by pimterry** [comment]
Great research, thanks for looking into this @nktnet1! That's really helpful.

> node-datachannel's package.json is missing a "main" field

That shouldn't be required though, as it does have an exports map which maps `.` (the root package export) to the correct file.

This resolution seems to work fine for CJS normally (`require('node-datachannel')` fails, but correctly reports the lib/index.js file as the problem, so it's clearly resolving it OK).

Any idea why that's not working here?

The latter `const require` issue is an easier fix, or could plausibly be something fixable automatically within ESM during processing, as part of the ESM->CJS transformation, but I'm not sure I understand why the `main` package.json field is required here, and I'm sure there will be plenty of other packages with that same issue.

**Comment by pimterry** [comment]
Regarding `const require`, it looks like this is quite a common pattern - https://github.com/search?q=%22const+require+%3D+createRequire%22&type=code shows 14k examples of the same thing on GitHub :grimacing:. That's going to cause problems. I think this is what you need to do to do a synchronous require within ESM, and `const require = ...` is the standard example for this (straight from the [node docs](https://nodejs.org/docs/latest/api/module.html#modulecreaterequirefilename) so that will break lots of things.

Fortunately, I think I've found a way to fix this within the esm package itself! I'll look into that further now and set up a little demo to test that.

Would you be open to switching to an esm fork to use that, if this works? The original package seems now unmaintained for years. Looks like https://github.com/wallabyjs/esm is actively maintained (as part of [wallaby.js](https://wallabyjs.com/)) and has done some useful updates in the meantime (updating Acorn, so it can parse modern syntax like `??`) so that might be a good base.

I think we could set up a fork based on that (I'm assuming the wallaby team aren't interested in these contributions, but who knows) with changes to fix `const require` and exports map resolution. With those in place, this package would appear be a rock solid solution to using ESM from CJS, which would be really _really_ useful. I'm here looking for exactly that - I'm trying to migrate a bunch of projects to ESM, and I desperately need a good option like this to be able to do so incrementally (without having to do a big-bang conversion to ESM at the top level before I can even start).

I think there's likely to be a widespread need for this as more projects start to try to migrate. Let me know if this is more hassle than you were looking for for this project though - I'm happy to fork and hack together my own solution on top instead, if that's easier.

**Comment by pimterry** [comment]
All done! I have two branches with esm package fixes here:

* Fixing `const require`: https://github.com/httptoolkit/esm/commit/c6d40cb4ebe6a24463be9980628e5220460bceba
* Falling back to Node's own resolution for modules that can't be found: https://github.com/httptoolkit/esm/commit/ff7df95c2e09cf2a6717532c8d0e8e9a1b6ff7d8

Neither is perfect, I can't claim to deeply understand all of esm, but they work and they both only affect cases that would otherwise _definitely_ fail (missing modules, and top-level redeclarations of `require`).

With those included, using the result with this package I can sync-import node-datachannel no problem at all, and every other ESM-only package I've tried (like node-fetch) all still works as normal. So far 100% success rate :muscle:

Are you open to integrating this?

**Comment by nktnet1** [comment]
Wow, this is amazing @pimterry 🎉!

I've been digging into esm's codebase myself and was able to make some progress, but couldn't get it to work.

---

> Would you be open to switching to an esm fork to use that, if this works

Yep, that's something I've had in mind for a while, just that import-sync has been able to find a workaround with a few hacks. Now's probably a good time for change though.

> Are you open to integrating this?

Of course :) - would you like to publish [@httptoolkit/esm](https://github.com/httptoolkit/esm) to GitHub or npm? I will look into the wallaby base and see if there are conflicts/duplications with import-sync and fix those up.
