### ISSUE TITLE
process is not defined

### ISSUE THREAD

**Issue by fonziemedia** [nktnet1/import-sync#8]
Hello,

First of all thanks for taking the time to build/share this package.

I'm running this on an old project that has a foundation built around 'sync requires' and this package is perfect if I can get it to work but I'm getting:

Uncaught ReferenceError: process is not defined
    at node_modules/esm/esm.js (esm.js:1:186)
    at __require2 (chunk-AUZ3RYOM.js?v=2899e366:18:50)
    at import.ts:1:17

The error is trigger upon importing:
`import importSync from "import-sync";`

Note that I have to install node-modules with --legacy-peer-deps because it's an old neglected mess so not sure if a peer dependency might be breaking this but I don't think so.. I've check that the esm module installed is the latest.

Let me know if you need more details from me, thanks!

**Comment by nktnet1** [comment]
Hi @fonziemedia,

Thank you for reaching out. 

Could you provide a minimal reproducible example for this issue? Other information such as your node version and the content of your package.json would help.

Note that unfortunately, **import-sync** only works with NodeJS (server-side), not client-side (e.g. frontend development and the like). If your project is indeed NodeJS, please first confirm that you are able to access NodeJS [process](https://nodejs.org/api/process.html) - e.g. as simple as
```
console.log(process);
```

Finally, the error suggests that the issue may lie with the [esm](https://github.com/standard-things/esm) module, a dependency of **import-sync**. It may be worth it to look through the issues in that project too to see if there are any workarounds :).

**Comment by fonziemedia** [comment]
Hey thanks for the quick response.

I'm indeed trying to run it for a frontend application running node 20.8.0 with vite 

I guess I'll have to look for for another way to go around the issues I'm experiencing but thanks anyway :)

**Comment by nktnet1** [comment]
@fonziemedia you can maybe try your luck with this module
- https://www.npmjs.com/package/require-esm-in-cjs

although there are some performance implications to consider, for example as a result of using [deasync](https://www.npmjs.com/package/deasync). Hope this points you in the right direction though :).

**Comment by fonziemedia** [comment]
Hey @nktnet1 

Thanks for the suggestion but it seems require-esm-in-cjs is also server-side only.. 

By the way, the error I was getting was actually related to vite:
https://github.com/vitejs/vite/issues/1973

I've managed to fix it but then I started getting other errors related to node.. 🤷 I guess I'll just have to do some refactoring of the project..

Thanks again for your help!

**Comment by nktnet1** [comment]
Found this fork of fractal that uses Vite and import-sync together:
- https://github.com/Schleuse/fractal

so I'm not so sure about my comment regarding only server-side NodeJS anymore 🤷 

e.g. it's being used here in ./packages/react/src/adapter.js#L13:
- https://github.com/Schleuse/fractal/blob/a05bde7c8cb2788e296f5ffda859e46debbbcd39/packages/react/src/adapter.js#L13

Maybe there is a configuration somewhere that allows the esm module to work.

**Comment by nktnet1** [comment]
In case you're still interested in solving this issue, I suggest looking into a package called Jiti:

- https://github.com/unjs/jiti

Example conversion here:

- https://github.com/nktnet-bug-report/import-sync-test/pull/1
